services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_gateway
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: gateway_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./backend
    container_name: gateway_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  checkout:
    build: ./checkout-page
    container_name: gateway_checkout
    ports:
      - "3001:80"
    depends_on:
      - api

  dashboard:
    build: ./frontend
    container_name: gateway_dashboard
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pgdata:
